const Database = require('better-sqlite3');
const db = new Database('costwatch.db');
db.pragma('journal_mode = WAL');
const schema = db.prepare("SELECT sql FROM sqlite_master WHERE name='config'").get();
console.log('Config schema:', schema?.sql);
const config = db.prepare('SELECT * FROM config').all();
console.log('Config rows:', config.length);
config.forEach(r => console.log(`  user=${r.user_id} key=${r.key} value=${r.value?.substring(0, 50)}`));
const users = db.prepare('SELECT id, email FROM users').all();
console.log('Users:', users);
db.close();
